apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mongo-user-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  nfs:
    path: /var/nfs/kubedata
    server: 3.75.94.251
