apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mongo-user-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  nfs:
    path: /nfs/mongodb-pvc
    server: 40.113.99.83
