apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
spec:
  destination:
    name: in-cluster
    namespace: applications
  project: default
  source:
    repoURL: https://github.com/hakobmkoyan771/infra.git
    path: Databases
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
