apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  #type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      targetPort: mongoport
      protocol: "TCP"
  selector:
    db: mongo
