apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    dbapp: contacts
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongo
  serviceName: mongodb-svc
  template:
    metadata:
      labels:
        db: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - name: mongoport
              containerPort: 27017
          readinessProbe:
            httpGet:
              path: /
              port: 27017
            successThreshold: 1
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 27017
            successThreshold: 1
            initialDelaySeconds: 40
            failureThreshold: 3
            periodSeconds: 10
          imagePullPolicy: Always
          volumeMounts:
            - name: mongodb-user-data
              mountPath: /data/db
      volumes:
        - name: mongodb-user-data
          persistentVolumeClaim:
            claimName: mongodb-userlist-pvc       
