apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6IlpHVjJiM0J6ZEdGemEyRmpjakU2ZERaRGJrdHFOR05IYlRKV1YyOVdSVnBCUVZGR1Ywd3daazFVWkdackswUT0ifX19
kind: Secret
metadata:
  name: webapps-reg-secret
type: kubernetes.io/dockerconfigjson
