apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkZXZvcHN0YXNrYWNyMS5henVyZWNyLmlvIjp7ImF1dGgiOiJaR1YyYjNCemRHRnphMkZqY2pFNk9HVXljRFppZFQxR1dHSTJZVkpoY1U1MlJHeHBkbEowUTFrd05sWnNRVUk9In19fQ==
kind: Secret
metadata:
  name: webapps-reg-secret
type: kubernetes.io/dockerconfigjson
